<?php

// these are also defined/used in "WebAPIInterface.cpp". make sure to update everywhere
const NO_ERR=0;
const BAD_USERNAME_ERROR_CODE = -1;
const BAD_PASSWORD_ERROR_CODE = -2;
const BAD_MISSIN_STAMP_ERROR_CODE = -3;
const BAD_MISSIN_HWKEY_ERROR_CODE = -4;
const BANNED_USER_ERROR_CODE = -5;
const MISSING_EMAIL_FIELD = -6;
const INVALID_RECOVERY_EMAIL = -7;
const FAILED_TO_CREATE_DB_ENTRY = -8;
const FAILED_TO_SEND_EMAIL = -9;
const INVALID_SESSION = -10;
const MISSING_PARAMETERS = -11;
const INVALID_USER = -12;
const NON_ACTIVE_USER = -13;
const NO_API_ACCESS = -14;
const SESSION_EXPIRED = -15;
const SESSION_SALT_MISMATCH = -16;
const NOT_ENOUGH_RIGHTS = -17;
const INVALID_TABLE_NAME = -18;
const CURL_ERROR_GENERIC = -19;
const BAD_TOKEN_ERROR_CODE = -20;

// this is also defined in SQL table 'UserActiveStates'
const USER_IS_ACTIVE_USABLE = 1;

// these are also defined in UserRoleDefines Make sure they are in sync

// must match with DB values !
const USER_RIGHT_VIEW_OTHER_ORGANIZATIONS = 400;	// this will allow viewing data of other organizations
const USER_RIGHT_UPDATE_OTHER_ORGANIZATIONS = 401;	// this will allow editing data of other organizations
const USER_RIGHT_VIEW_OTHER_USER = 450;	
const USER_RIGHT_UPDATE_OTHER_USER = 451;

const USER_RIGHT_ID_VIEW_USER_INFO = 20;
const USER_RIGHT_ID_UPDATE_USER_INFO = 40;
const USER_RIGHT_ID_VIEW_ACTIVITY_LOG = 90;
const USER_RIGHT_ID_CREATE_ALERT = 120;
const USER_RIGHT_ID_VIEW_ALERTS = 130;
const USER_RIGHT_ID_CREATE_LOCATION = 280;
const USER_RIGHT_ID_VIEW_LOCATION = 290;
const USER_RIGHT_ID_UPDATE_LOCATION = 300;
const USER_RIGHT_ID_DELETE_LOCATION = 310;
const USER_RIGHT_ID_CREATE_MODULE = 320;
const USER_RIGHT_ID_VIEW_MODULES = 330;
const USER_RIGHT_ID_UPDATE_MODULES = 340;
const USER_RIGHT_ID_DELETE_MODULE = 350;
const USER_RIGHT_ID_SAVE_KPI_DATA = 360;
const USER_RIGHT_ID_SAVE_CRASH_DATA = 370;
const USER_RIGHT_ID_FETCH_DPS_SERVERS = 380;

// Organization rights are not implemented, but supported
const ORGANIZATION_RIGHT_VIEW_ACTIVITY = 0; 
const ORGANIZATION_RIGHT_CREATE_ALERT = 0; 
const ORGANIZATION_RIGHT_VIEW_ALERTS = 0; 
const ORGANIZATION_RIGHT_CREATE_LOCATIONS = 0; 
const ORGANIZATION_RIGHT_VIEW_LOCATIONS = 0; 
const ORGANIZATION_RIGHT_UPDATE_LOCATIONS = 0; 
const ORGANIZATION_RIGHT_DELETE_LOCATIONS = 0; 
const ORGANIZATION_RIGHT_CREATE_MODULES = 0;
const ORGANIZATION_RIGHT_VIEW_MODULES = 0; 
const ORGANIZATION_RIGHT_UPDATE_MODULES = 0; 
const ORGANIZATION_RIGHT_DELETE_MODULES = 0;
const ORGANIZATION_RIGHT_VIEW_USERS = 0; 
const ORGANIZATION_RIGHT_UPDATE_USERS = 0; 
const ORGANIZATION_RIGHT_SAVE_KPI_DATA = 0; 
const ORGANIZATION_RIGHT_SAVE_CRASH_DATA = 0; 
const ORGANIZATION_RIGHT_ID_FETCH_DPS_SERVERS = 0; 

// shared between multiple projects
const LOG_GROUP_BACKEND = 2;

// these are backend specific
const LOG_SOURCE_LOGIN = 1;
const LOG_SOURCE_PASSWCHANGE = 2;
const LOG_SOURCE_LOG = 3;
const LOG_SOURCE_USER_ACTION = 4;

const LOG_SEVERITY_NORMAL = 4;

const MFA_TYPE_PWD_LOGIN = 1;
const MFA_TYPE_EMAIL_TOKEN = 2;
const MFA_TYPE_SMS_TOKEN = 3;

?>