# Component directories

COMMON_DIR:=$(PROJECT_ROOT)/common
DAOS_DIR:=$(PROJECT_ROOT)/daos
LOGGER_DIR:=$(PROJECT_ROOT)/logger
FILE_CLIENT_DIR:=$(PROJECT_ROOT)/fs_client
FILE_SERVER_DIR:=$(PROJECT_ROOT)/fs_server
PROFILING_DIR:=$(PROJECT_ROOT)/profiling
UTILS_DIR:=$(PROJECT_ROOT)/utils
3RDPARTY_DIR:=$(PROJECT_ROOT)/3rdparty
ERROR_REPORTING_DIR=$(PROJECT_ROOT)/error_reporting
