[Global]
# Logging will have a great perfomance hit on the application. Probably should only enable it while debugging
EnableLogging=True
# Will write to log file any log that is below the requested severity
LogSeverity=Debug

[BufferPool]
# should be larger than the largest block to be allocated in code
BlockAllocSize=2097152
# this is wasted memory, should be larger than an average alloc size
MinFreeToKeep=512
# number of pools to create for pool manager on startup
InitialBufferPools=10
# number of elements allocated by default to struct pools. Mostly used when creating new flows
InitialStructPoolElements=100

[MySQL]
# where to connect to
Host=172.22.16.1
# use default port
Port=3306
User=admin
Passw=admin
DBName=app_dissector

[Plugins]
# the first plugin confindence score higher than this will abort searching for a better application match
# ex : if server IP says it's only used for airbnb + american express, it will have a confidence score of 0.5 . This can block TLS plugin for processing the flow
ConfidenceTreshold=0.5
# Can disable individiual plugins if desired
Disable_JA3S=0
Disable_JA4C=0
Disable_IP=0
Disable_DNS=0
Disable_Certificate=0
