#ifndef _APP_ERRORS_H_
#define _APP_ERRORS_H_

typedef enum SimilarityServiceAppErrorCodes
{
    ERR_SS_NO_ERROR = 0,
    ERR_SS_UNKNOWN_SCORE_TYPE = 1,
    ERR_SS_NETWORK_SIZE_FILE_SIZE_MISMATCH = 2,
    ERR_SS_FAILED_TO_OPEN_FILE_FOR_WRITE = 3,
    ERR_SS_FILE_WRITE_NOT_COMPLETED = 4,
    ERR_SS_VALUE_NOT_INITIALIZED = 5,
    ERR_SS_PACKET_SIZE_TOO_LARGE = 6,
    ERR_SS_SOCKET_READ_NOT_ENOUGH_BYTES = 7,
    ERR_SS_SOCKET_WRITE_INTERRUPTED = 8,
    ERR_SS_NON_HANDLED_PACKET_TYPE = 9,
    ERR_SS_UNKNOWN_PACKET_TYPE = 10,
    ERR_SS_MEMORY_ALLOC_FAILED = 11,
    ERR_SS_ID_ARRAY_TOO_LARGE = 12,
    ERR_SS_FAILED_TO_OPEN_FILE_FOR_READ = 13,
    ERR_SS_FAILED_TO_MAP_FILE_FOR_READ = 14,
    ERR_SS_FAILED_TO_UNMAP_FILE = 15,
    ERR_SS_NO_INPUT_SIMILARITY_FILES = 16,
    ERR_SS_FAILED_TO_PARSE_GET_REQUEST_DATA = 17,
    ERR_SS_MALFORMED_END_CONNECTION_PACKET = 18,
    ERR_SS_MALFORMED_PING_PACKET = 19,
    ERR_SS_MALFORMED_GET_SCORE_PACKET = 20,
    ERR_SS_FAILED_TO_INITIALIZE_RW_LOCK = 21,
    ERR_SS_FAILED_TO_UNITIALIZE_RW_LOCK = 22,
    ERR_SS_FAILED_TO_READ_LOCK = 23,
    ERR_SS_FAILED_TO_WRITE_LOCK = 24,
    ERR_SS_FAILED_TO_UNLOCK_READ_LOCK = 25,
    ERR_SS_FAILED_TO_UNLOCK_WRITE_LOCK = 26,
    ERR_SS_ID_ARRAY_EMPTY = 27,
    ERR_SS_FAILED_TO_CLOSE_FILE = 28,
    ERR_SS_SCORE_FILE_COUNT_UNEXPECTED = 29,
    ERR_SS_SCORE_FILE_COUNT_BAD = 30,
    ERR_SS_SCORE_FILE_PADDING_BAD = 31,
    ERR_SS_FILE_READ_FAILED = 32,
    ERR_SS_SCORE_ID_TOO_LARGE = 33,
    ERR_SS_THREAD_CREATE_FAILED = 34,
    ERR_SS_FAILED_TO_SPLIT_MT_WORK = 35,
    ERR_SS_FAILED_TO_PREPARE_INPUT_FILE = 36,
    ERR_SS_MAX_KNOWN // make sure always the last
}SimilarityServiceAppErrorCodes;

static const char *g_err_code_str[ERR_SS_MAX_KNOWN] __attribute__((unused)) =
{
    [ERR_SS_NO_ERROR] = "No error",
    [ERR_SS_UNKNOWN_SCORE_TYPE] = "Unknown similarity score type",
    [ERR_SS_NETWORK_SIZE_FILE_SIZE_MISMATCH] = "Network bytes count does not match similarity score file size",
    [ERR_SS_FAILED_TO_OPEN_FILE_FOR_WRITE] = "Failed to open score file for writing",
    [ERR_SS_FILE_WRITE_NOT_COMPLETED] = "Failed to write all bytes to file",
    [ERR_SS_VALUE_NOT_INITIALIZED] = "Value has not been initialized",
    [ERR_SS_PACKET_SIZE_TOO_LARGE] = "Packet size is greater than max allowed",
    [ERR_SS_SOCKET_READ_NOT_ENOUGH_BYTES] = "Failed to read full packet from network",
    [ERR_SS_SOCKET_WRITE_INTERRUPTED] = "Failed to write full packet to network",
    [ERR_SS_NON_HANDLED_PACKET_TYPE] = "No handler attached to packet type",
    [ERR_SS_UNKNOWN_PACKET_TYPE] = "Unknown packet type",
    [ERR_SS_MEMORY_ALLOC_FAILED] = "Failed to allocate memory",
    [ERR_SS_ID_ARRAY_TOO_LARGE] = "Similarity ID array size too large",
    [ERR_SS_FAILED_TO_OPEN_FILE_FOR_READ] = "Failed to open score file for reading",
    [ERR_SS_FAILED_TO_MAP_FILE_FOR_READ] = "Failed to map score file for reading",
    [ERR_SS_FAILED_TO_UNMAP_FILE] = "Failed to unmap score file",
    [ERR_SS_NO_INPUT_SIMILARITY_FILES] = "Found no similarity files to process",
    [ERR_SS_FAILED_TO_PARSE_GET_REQUEST_DATA] = "Failed to parse get request data block",
    [ERR_SS_MALFORMED_END_CONNECTION_PACKET] = "Malformed end connection packet",
    [ERR_SS_MALFORMED_PING_PACKET] = "Malformed ping packet",
    [ERR_SS_MALFORMED_GET_SCORE_PACKET] = "Malformed get scores packet",
    [ERR_SS_FAILED_TO_INITIALIZE_RW_LOCK] = "Failed to initialize RW lock",
    [ERR_SS_FAILED_TO_UNITIALIZE_RW_LOCK] = "Failed to unitialize RW lock",
    [ERR_SS_FAILED_TO_READ_LOCK] = "Failed to aquire read lock",
    [ERR_SS_FAILED_TO_WRITE_LOCK] = "Failed to aquire write lock",
    [ERR_SS_FAILED_TO_UNLOCK_READ_LOCK] = "Failed to release read lock",
    [ERR_SS_FAILED_TO_UNLOCK_WRITE_LOCK] = "Failed to release write lock",
    [ERR_SS_ID_ARRAY_EMPTY] = "Request ID array is empty",
    [ERR_SS_FAILED_TO_CLOSE_FILE] = "Failed to close file",
    [ERR_SS_SCORE_FILE_COUNT_UNEXPECTED] = "Score file contained unexpected count",
    [ERR_SS_SCORE_FILE_COUNT_BAD] = "Score file count points outside score file",
    [ERR_SS_SCORE_FILE_PADDING_BAD] = "Score file padding was expected to be 0",
    [ERR_SS_FILE_READ_FAILED] = "Failed to read enough bytes from file",
    [ERR_SS_SCORE_ID_TOO_LARGE] = "Score ID larger than anticipated",
    [ERR_SS_THREAD_CREATE_FAILED] = "Failed to create Thread",
    [ERR_SS_FAILED_TO_SPLIT_MT_WORK] = "Failed to fairly split work between WorkerThreads",
    [ERR_SS_FAILED_TO_PREPARE_INPUT_FILE] = "Failed to prepare file content to be merged"
};

#define LOG_DEFAULT_APP_ERROR(err) LOG_MESSAGE(ATTENTION_LOG_MSG, "Error: %d = %s", \
    err, g_err_code_str[err]);
#endif