# Component directories

3RDPARTY_DIR:=$(PROJECT_ROOT)/3rdparty
COMMON_DIR:=$(PROJECT_ROOT)/common
ASSERT_MT_DIR:=$(PROJECT_ROOT)/assert_mt
LOGGER_DIR:=$(PROJECT_ROOT)/logger
SS_CLIENT_DIR:=$(PROJECT_ROOT)/ss_client
SS_SERVER_DIR:=$(PROJECT_ROOT)/ss_server
PROFILING_DIR:=$(PROJECT_ROOT)/profiling
UTILS_DIR:=$(PROJECT_ROOT)/utils
SCORE_MANAGER_DIR:=$(PROJECT_ROOT)/score_manager
ERROR_REPORTING_DIR=$(PROJECT_ROOT)/error_reporting
