#ifndef BINARY_SPECIALIZED_ARRAY_H
#define BINARY_SPECIALIZED_ARRAY_H

#include <binary_array.h>
#include <binary_utils.h>
#include <stdint.h>

//
// int32_t
//

#define INT32_ARRAY_TO_BINARY(ARRAY, BYTESTREAM, OFFSET) \
    VALUE_ARRAY_TO_BINARY(ARRAY, int32ToBinary, BYTESTREAM, OFFSET)

#define BINARY_TO_INT32_ARRAY(ARRAY, BYTESTREAM, OFFSET) \
    BINARY_TO_ARRAY(int32_t, ARRAY, binaryToInt32, DUMMY_INIT, DUMMY_FREE, BYTESTREAM, OFFSET)

//
// char*
//

#define STRING_ARRAY_TO_BINARY(ARRAY, BYTESTREAM, OFFSET) \
    VALUE_ARRAY_TO_BINARY(ARRAY, stringToBinary, BYTESTREAM, OFFSET)

#define INIT_STRING(STR) do { *STR = NULL; } while(false)

#define FREE_STRING(STR) do { free(*STR); *STR = NULL; } while(false)

#define BINARY_TO_STRING_ARRAY(ARRAY, BYTESTREAM, OFFSET) \
    BINARY_TO_ARRAY(char*, ARRAY, binaryToString, INIT_STRING, FREE_STRING, BYTESTREAM, OFFSET)

#define STRING_BINARY_SIZE(STR) stringBinarySize(*(STR))

#define STRING_ARRAY_BINARY_SIZE(ARRAY, TOTAL_SIZE) \
    VARIABLE_ARRAY_BINARY_SIZE(ARRAY, STRING_BINARY_SIZE, TOTAL_SIZE)

#endif // BINARY_SPECIALIZED_ARRAY_H
