"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small.asf ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small.flv ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small.webm ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small.mov ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small.mpegts ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small.ogv ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_flashsv.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_h263.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_hevc.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_huffyuv.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_jpeg2000.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_mpeg2video.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_msmpeg4v3.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_qtrle.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_theora.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_vp8.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_vp9.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_wmv1.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_noaudio.avi ShowFrameInfo=1
"./x64/debug/DesktopPlayer.exe" in=../TestSamples/small_novideo.avi ShowFrameInfo=1