# Component directories

3RDPARTY_DIR:=$(PROJECT_ROOT)/3rdparty
COMMON_DIR:=$(PROJECT_ROOT)/common
ASSERT_MT_DIR:=$(PROJECT_ROOT)/assert_mt
CACHE_ENGINE_DIR:=$(PROJECT_ROOT)/cache_engine
DAOS_DIR:=$(PROJECT_ROOT)/daos
FILTERS_DIR:=$(PROJECT_ROOT)/filters
LOGGER_DIR:=$(PROJECT_ROOT)/logger
PROFILE_CLIENT_DIR:=$(PROJECT_ROOT)/profile_client
PROFILE_SERVER_DIR:=$(PROJECT_ROOT)/profile_server
PROFILING_DIR:=$(PROJECT_ROOT)/profiling
SCORING_DIR:=$(PROJECT_ROOT)/scoring
SEARCH_DIR:=$(PROJECT_ROOT)/search
TEST_UTILS_DIR:=$(PROJECT_ROOT)/test_utils
UTILS_DIR:=$(PROJECT_ROOT)/utils
ERROR_REPORTING_DIR=$(PROJECT_ROOT)/error_reporting
DB_MIGRATION_DIR:=$(PROJECT_ROOT)/tools/db_migration
MODELS_DIR:=$(PROJECT_ROOT)/models
COMPARISON_DIR:=$(MODELS_DIR)/comparison
TEST_DATA_DIR:=$(MODELS_DIR)/test_data
ITEM_FUNCTIONS_DIR:=$(PROJECT_ROOT)/item_functions
