apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
    - port: 80
      name: server
  clusterIP: None
  selector:
    app: scoring-client-${ENV}-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scoring-client-${ENV}-server
spec:
  serviceName: server
  podManagementPolicy: "Parallel"
  replicas: ${NUM_EXTERNAL_SHARDS}
  selector:
    matchLabels:
      app: scoring-client-${ENV}-server
  template:
    metadata:
      labels:
        app: scoring-client-${ENV}-server
        spotinst.io/restrict-scale-down: "true"
      annotations:
        karpenter.sh/do-not-evict: "true"
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      containers:
        - name: scoring-client-${ENV}-server
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}:${CIRCLE_SHA1}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "${KUBERNETES_CPU}"
            limits:
              memory: "${KUBERNETES_RAM}"
              ephemeral-storage: 8Gi
          command: [ "/bin/bash", "-c" ]
          args:
            - ./ferrari_server.sh
          envFrom:
            - configMapRef:
                name: scoring-client-${ENV}-config
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: ${PORT}
          volumeMounts:
            - name: www
              mountPath: /scoring-client/data
      terminationGracePeriodSeconds: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: karpenter.sh/capacity-type
                    operator: In
                    values:
                      - on-demand
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - ${INSTANCE_TYPE}
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-east-1c  
      tolerations:
        - key: "singlezone"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: ${KUBERNETES_DISK}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scoring-client-${ENV}-config
data:
  ENV: "${ENV}"
  KUBERNETES_CPU: "${KUBERNETES_CPU}"
  PORT: "${PORT}"
  NUM_EXTERNAL_SHARDS: "${NUM_EXTERNAL_SHARDS}"
  NUM_PROFILE_CACHE_ENTRIES: "${NUM_PROFILE_CACHE_ENTRIES}"
  NUM_COMPANY_CACHE_ENTRIES: "${NUM_COMPANY_CACHE_ENTRIES}"
  NUM_CONNECTIONS: "${NUM_CONNECTIONS}"
  NUM_SEARCH_THREADS: "${NUM_SEARCH_THREADS}"
  LOG_LEVEL: ${LOG_LEVEL}
  NUM_LOADING_THREADS: "${NUM_LOADING_THREADS}"
  CONNECTION_TIMEOUT: "${CONNECTION_TIMEOUT}"
  REQUEST_ARRIVAL_TIMEOUT: "${REQUEST_ARRIVAL_TIMEOUT}"
  SENTRY_DSN: "${SENTRY_DSN}"
  SENTRY_RELEASE: "${CIRCLE_SHA1}"
  SENTRY_ENVIRONMENT: "${ENV}"
