#ifndef _PROFILE_PERSISTENT_2_H_
#define _PROFILE_PERSISTENT_2_H_

#include "serialize_generic.h"

// always update this in case you add new fields
#define PROFILE_PERSISTENT_WRITER_VERSION 1

// If you add new fields, reorder fields, you will not be able to read old data anymore
typedef enum ProfilePersistentFieldNames
{
	PPFN_ID = GSSFN_MAX_FIELD_NAME,
	PPFN_FIRST_NAME,
	PPFN_LAST_NAME,
	PPFN_ARCHIVED_PRIMARY_EMAIL,
	PPFN_LINKEDIN_USER,
	PPFN_PROFILE_CODE,
	PPFN_PROFILE_KEY,
	PPFN_HEADLINE,
	PPFN_SUMMARY,
	PPFN_IMAGE_URL,
	PPFN_INDUSTRY,
	PPFN_LINKEDINURL,
	PPFN_NUM_CONNECTIONS,
	PPFN_SOURCE,
	PPFN_BATCH,
	PPFN_COVID19,
	PPFN_LINKEDIN_CANONICAL_URL,
	PPFN_LINKEDIN_CANONICAL_USER,
	PPFN_LINKEDIN_ID,
	PPFN_SOURCE_KEY,
	PPFN_LOCALITYID,
	PPFN_LOCATION,
	PPFN_COUNTRY,
	PPFN_LOGICAL_DELETE,
	PPFN_GENDER,
	PPFN_ETHNICITY,
	PPFN_LAST_CACHED_AT,
	PPFN_LAST_MESSAGED,
	PPFN_LAST_REPLIED,
	PPFN_LAST_POSITIVE_REPLIED,
	PPFN_GROUPS,
	PPFN_PROJECTS,
	PPFN_ATS_COMPANIES,
	PPFN_ATS_STATUS,
	PPFN_ATS_LAST_ACTIVITY,
	PPFN_ACTIONED,
	PPFN_POSITIONS,
	PPFN_EDUCATION,
	PPFN_SKILLS,
	PPFN_PROFILE_EMAILS,
	PPFN_PROFILE_SOCIAL_URLS,
	PPFN_PROFILE_PHONE_NUMBERS,
	PPFN_PROFILE_TAGS,
	PPFN_FULL_NAME_STANDARDIZED,
	PPFN_HEADLINE_STANDARDIZED,
	PPFN_SUMMARY_STANDARDIZED,
	PPFN_MAX_FIELD_NAME
}ProfilePersistentFieldNames;

#endif